.F.
======================================================================
FAIL: test_dimension_payment_details_insertion (ut.check_student)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\umapriya.krishnan\Desktop\student_project\Student_project-kanth_feature\src\test\ut.py", line 50, in test
    self.assertEqual(comp1 == [], True, msg=table + " " + str(comp1))
AssertionError: False != True : dimension_payment_details [('FEE6', 1000, 'ARREAR FEE', datetime.datetime(2020, 7, 29, 0, 0), datetime.datetime(9999, 12, 31, 0, 0))]

----------------------------------------------------------------------
Ran 3 tests in 0.509s

FAILED (failures=1)
