2020-07-20 12:26:25,172 - 27652 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/k.a.ramasubramanian/Desktop/Training/Student_project/src/main/creation_ddl_update.py", line 59, in ddl_updates\n    self.obj2.create_table(table, filepath)\n', "AttributeError: 'execution' object has no attribute 'create_table'\n"]
2020-07-20 12:27:04,738 - 27528 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/k.a.ramasubramanian/Desktop/Training/Student_project/src/main/creation_ddl_update.py", line 52, in ddl_updates\n    db_table = mycursor.fetchone()[1].lstrip(table).strip("ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci").replace("`", "").replace("\\n","").replace("  ", "").replace(table.lower() + " (", "").replace(", ", " ,").lower().replace("not null", "").split("key")[0].replace("default null", "").split(",")\n', "AttributeError: 'int' object has no attribute 'fetchone'\n"]
2020-07-20 12:27:54,095 - 28024 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/k.a.ramasubramanian/Desktop/Training/Student_project/src/main/creation_ddl_update.py", line 59, in ddl_updates\n    self.obj2.create_table(table, filepath)\n', "AttributeError: 'execution' object has no attribute 'create_table'\n"]
